spring.application.name=jpa_relacionamentos

# Habilita o H2 Console
spring.h2.console.enabled=true

# Altera o caminho de acesso (Opcional - o padrão já é /h2-console)
spring.h2.console.path=/h2-console

# Configura a URL do banco de dados em memória (para os dados não sumirem toda hora)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver

# Usuário e senha padrão para logar no console
spring.datasource.username=sa
spring.datasource.password=